version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running database migrations"
      - python manage.py migrate
      - echo "Running tests"
      - python manage.py test
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
